// Header
#include "CommutationTable.h"

#define COMM_POTOutToPOT1 					(uint64_t) 1 << 12
#define COMM_POTOutToPOT2 					(uint64_t) 1 << 13
#define COMM_POTOutToPOT3 					(uint64_t) 1 << 14
#define COMM_POTOutToPOT4 					(uint64_t) 1 << 15
#define COMM_POTOutToPOT5 					(uint64_t) 1 << 16
#define COMM_POTOutToPOT6 					(uint64_t) 1 << 17

#define COMM_POTPlusToPOT1 					(uint64_t) 1 << 0 | COMM_POTOutToPOT1
#define COMM_POTPlusToPOT2 					(uint64_t) 1 << 1 | COMM_POTOutToPOT2
#define COMM_POTPlusToPOT3 					(uint64_t) 1 << 2 | COMM_POTOutToPOT3
#define COMM_POTPlusToPOT4 					(uint64_t) 1 << 3 | COMM_POTOutToPOT4
#define COMM_POTPlusToPOT5 					(uint64_t) 1 << 4 | COMM_POTOutToPOT5
#define COMM_POTPlusToPOT6 					(uint64_t) 1 << 5 | COMM_POTOutToPOT6

#define COMM_POTMinusToPOT1 				(uint64_t) 1 << 6 | COMM_POTOutToPOT1
#define COMM_POTMinusToPOT2 				(uint64_t) 1 << 7 | COMM_POTOutToPOT2
#define COMM_POTMinusToPOT3 				(uint64_t) 1 << 8 | COMM_POTOutToPOT3
#define COMM_POTMinusToPOT4 				(uint64_t) 1 << 9 | COMM_POTOutToPOT4
#define COMM_POTMinusToPOT5 				(uint64_t) 1 << 10 | COMM_POTOutToPOT5
#define COMM_POTMinusToPOT6 				(uint64_t) 1 << 11 | COMM_POTOutToPOT6

#define COMM_Ctrl1ToCtrl1 					(uint64_t) 1 << 30
#define COMM_Ctrl1ToCtrl2 					(uint64_t) 1 << 31
#define COMM_Ctrl1ToCtrl3 					(uint64_t) 1 << 32
#define COMM_Ctrl1ToCtrl4 					(uint64_t) 1 << 33
#define COMM_Ctrl2ToCtrl1 					(uint64_t) 1 << 34
#define COMM_Ctrl2ToCtrl2 					(uint64_t) 1 << 35
#define COMM_Ctrl2ToCtrl3 					(uint64_t) 1 << 36
#define COMM_Ctrl2ToCtrl4 					(uint64_t) 1 << 37

#define COMM_PotCtrlPlusToCtrlPot1 			(uint64_t) 1 << 38
#define COMM_PotCtrlPlusToCtrlPot2 			(uint64_t) 1 << 39
#define COMM_PotCtrlPlusToCtrlPot3 			(uint64_t) 1 << 40
#define COMM_PotCtrlPlusToCtrlPot4 			(uint64_t) 1 << 41
#define COMM_PotCtrlMinusToCtrlPot1 		(uint64_t) 1 << 42
#define COMM_PotCtrlMinusToCtrlPot2 		(uint64_t) 1 << 43
#define COMM_PotCtrlMinusToCtrlPot3 		(uint64_t) 1 << 44
#define COMM_PotCtrlMinusToCtrlPot4 		(uint64_t) 1 << 45

#define COMM_BUSLVPlusToPOW1 				(uint64_t) 1 << 46
#define COMM_BUSLVPlusToPOW2 				(uint64_t) 1 << 47
#define COMM_BUSLVPlusToPOW3 				(uint64_t) 1 << 48
#define COMM_BUSLVPlusToPOW4 				(uint64_t) 1 << 49
#define COMM_BUSLVPlusToPOW5 				(uint64_t) 1 << 50
#define COMM_BUSLVPlusToPOW6 				(uint64_t) 1 << 51

#define COMM_BUSLVMinusToPOW1 				(uint64_t) 1 << 52
#define COMM_BUSLVMinusToPOW2 				(uint64_t) 1 << 53
#define COMM_BUSLVMinusToPOW3 				(uint64_t) 1 << 54
#define COMM_BUSLVMinusToPOW4 				(uint64_t) 1 << 55
#define COMM_BUSLVMinusToPOW5 				(uint64_t) 1 << 56
#define COMM_BUSLVMinusToPOW6 				(uint64_t) 1 << 57

const RegisterPin* const COMM_SimpleRelayArray[] = {&COMM_SwitchPOTPlusToPOT1,					// 0
		&COMM_SwitchPOTPlusToPOT2,					// 1
		&COMM_SwitchPOTPlusToPOT3,					// 2
		&COMM_SwitchPOTPlusToPOT4,					// 3
		&COMM_SwitchPOTPlusToPOT5,					// 4
		&COMM_SwitchPOTPlusToPOT6,					// 5

		&COMM_SwitchPOTMinusToPOT1,					// 6
		&COMM_SwitchPOTMinusToPOT2,					// 7
		&COMM_SwitchPOTMinusToPOT3,					// 8
		&COMM_SwitchPOTMinusToPOT4,					// 9
		&COMM_SwitchPOTMinusToPOT5,					// 10
		&COMM_SwitchPOTMinusToPOT6,					// 11

		&COMM_SwitchPOTOutToPOT1,					// 12
		&COMM_SwitchPOTOutToPOT2,					// 13
		&COMM_SwitchPOTOutToPOT3,					// 14
		&COMM_SwitchPOTOutToPOT4,					// 15
		&COMM_SwitchPOTOutToPOT5,					// 16
		&COMM_SwitchPOTOutToPOT6,					// 17

		&COMM_SwitchBUSHVPlusToPOW1,				// 18
		&COMM_SwitchBUSHVPlusToPOW2,				// 19
		&COMM_SwitchBUSHVPlusToPOW3,				// 20
		&COMM_SwitchBUSHVPlusToPOW4,				// 21
		&COMM_SwitchBUSHVPlusToPOW5,				// 22
		&COMM_SwitchBUSHVPlusToPOW6,				// 23

		&COMM_SwitchBUSHVMinusToPOW1,				// 24
		&COMM_SwitchBUSHVMinusToPOW2,				// 25
		&COMM_SwitchBUSHVMinusToPOW3,				// 26
		&COMM_SwitchBUSHVMinusToPOW4,				// 27
		&COMM_SwitchBUSHVMinusToPOW5,				// 28
		&COMM_SwitchBUSHVMinusToPOW6,				// 29

		&COMM_SwitchCtrl1ToCtrl1,					// 30
		&COMM_SwitchCtrl1ToCtrl2,					// 31
		&COMM_SwitchCtrl1ToCtrl3,					// 32
		&COMM_SwitchCtrl1ToCtrl4,					// 33
		&COMM_SwitchCtrl2ToCtrl1,					// 34
		&COMM_SwitchCtrl2ToCtrl2,					// 35
		&COMM_SwitchCtrl2ToCtrl3,					// 36
		&COMM_SwitchCtrl2ToCtrl4,					// 37

		&COMM_SwitchPotCtrlPlusToCtrlPot1,			// 38
		&COMM_SwitchPotCtrlPlusToCtrlPot2,			// 39
		&COMM_SwitchPotCtrlPlusToCtrlPot3,			// 40
		&COMM_SwitchPotCtrlPlusToCtrlPot4,			// 41
		&COMM_SwitchPotCtrlMinusToCtrlPot1,			// 42
		&COMM_SwitchPotCtrlMinusToCtrlPot2,			// 43
		&COMM_SwitchPotCtrlMinusToCtrlPot3,			// 44
		&COMM_SwitchPotCtrlMinusToCtrlPot4			// 45
		};

const BistableSwitch* const COMM_BistableRelayArray[] = {&COMM_SwitchBUSLVPlusToPOW1,				// 0 (46)
		&COMM_SwitchBUSLVPlusToPOW2,				// 1	(47)
		&COMM_SwitchBUSLVPlusToPOW3,				// 2	(48)
		&COMM_SwitchBUSLVPlusToPOW4,				// 3	(49)
		&COMM_SwitchBUSLVPlusToPOW5,				// 4	(50)
		&COMM_SwitchBUSLVPlusToPOW6,				// 5	(51)

		&COMM_SwitchBUSLVMinusToPOW1,				// 6	(52)
		&COMM_SwitchBUSLVMinusToPOW2,				// 7	(53)
		&COMM_SwitchBUSLVMinusToPOW3,				// 8	(54)
		&COMM_SwitchBUSLVMinusToPOW4,				// 9	(55)
		&COMM_SwitchBUSLVMinusToPOW5,				// 10	(56)
		&COMM_SwitchBUSLVMinusToPOW6				// 11	(57)
		};

// Aliases
#define ALIAS_CTRL1_DIRECT_POT				(COMM_Ctrl1ToCtrl1 | COMM_Ctrl2ToCtrl2 | COMM_PotCtrlPlusToCtrlPot1 | COMM_PotCtrlMinusToCtrlPot2)
#define ALIAS_CTRL1_DIRECT_NO_POT			(COMM_Ctrl1ToCtrl1 | COMM_Ctrl2ToCtrl2)
#define ALIAS_CTRL1_REVERSE_POT				(COMM_Ctrl1ToCtrl2 | COMM_Ctrl2ToCtrl1 | COMM_PotCtrlPlusToCtrlPot2 | COMM_PotCtrlMinusToCtrlPot1)

#define ALIAS_CTRL2_DIRECT_POT				(COMM_Ctrl1ToCtrl3 | COMM_Ctrl2ToCtrl4 | COMM_PotCtrlPlusToCtrlPot3 | COMM_PotCtrlMinusToCtrlPot4)
#define ALIAS_CTRL2_DIRECT_NO_POT			(COMM_Ctrl1ToCtrl3 | COMM_Ctrl2ToCtrl4)
#define ALIAS_CTRL2_REVERSE_POT				(COMM_Ctrl1ToCtrl4 | COMM_Ctrl2ToCtrl3 | COMM_PotCtrlPlusToCtrlPot4 | COMM_PotCtrlMinusToCtrlPot3)

#define ALIAS_HV1_DIRECT					(COMM_BUSHVPlusToPOW1 | COMM_BUSHVMinusToPOW2)
#define ALIAS_HV2_DIRECT					(COMM_BUSHVPlusToPOW3 | COMM_BUSHVMinusToPOW4)
#define ALIAS_HV3_DIRECT					(COMM_BUSHVPlusToPOW5 | COMM_BUSHVMinusToPOW6)

#define ALIAS_HV1_REVERSE					(COMM_BUSHVPlusToPOW2 | COMM_BUSHVMinusToPOW1)
#define ALIAS_HV2_REVERSE					(COMM_BUSHVPlusToPOW4 | COMM_BUSHVMinusToPOW3)
#define ALIAS_HV3_REVERSE					(COMM_BUSHVPlusToPOW6 | COMM_BUSHVMinusToPOW5)

#define ALIAS_POW1_DIRECT_POT				(COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | COMM_POTPlusToPOT1 | COMM_POTMinusToPOT2)
#define ALIAS_POW2_DIRECT_POT				(COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4 | COMM_POTPlusToPOT3 | COMM_POTMinusToPOT4)
#define ALIAS_POW3_DIRECT_POT				(COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4 | COMM_POTPlusToPOT3 | COMM_POTMinusToPOT4)

#define ALIAS_POW1_REVERSE_POT				(COMM_BUSLVPlusToPOW2 | COMM_BUSLVMinusToPOW1 | COMM_POTPlusToPOT2 | COMM_POTMinusToPOT1)
#define ALIAS_POW2_REVERSE_POT				(COMM_BUSLVPlusToPOW4 | COMM_BUSLVMinusToPOW3 | COMM_POTPlusToPOT4 | COMM_POTMinusToPOT3)
#define ALIAS_POW3_REVERSE_POT				(COMM_BUSLVPlusToPOW6 | COMM_BUSLVMinusToPOW5 | COMM_POTPlusToPOT6 | COMM_POTMinusToPOT5)

// Aliases A6
#define ALIAS_A6_HV2_DIRECT					(COMM_BUSHVPlusToPOW3 | COMM_BUSHVMinusToPOW2)
#define ALIAS_A6_HV2_REVERSE				(COMM_BUSHVPlusToPOW2 | COMM_BUSHVMinusToPOW3)

#define ALIAS_A6_POW2_DIRECT_POT			(COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW2 | COMM_POTPlusToPOT3 | COMM_POTMinusToPOT2)
#define ALIAS_A6_POW2_REVERSE_POT			(COMM_BUSLVPlusToPOW2 | COMM_BUSLVMinusToPOW3 | COMM_POTPlusToPOT2 | COMM_POTMinusToPOT3)

// Aliases E2k
#define ALIAS_E2k_HV2_DIRECT				(COMM_BUSHVPlusToPOW3 | COMM_BUSHVMinusToPOW1)
#define ALIAS_E2k_HV2_REVERSE				(COMM_BUSHVPlusToPOW1 | COMM_BUSHVMinusToPOW3)

#define ALIAS_E2k_POW2_DIRECT_POT			(COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW1 | COMM_POTPlusToPOT3 | COMM_POTMinusToPOT1)
#define ALIAS_E2k_POW2_REVERSE_POT			(COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW3 | COMM_POTPlusToPOT1 | COMM_POTMinusToPOT3)

// Variables
MeasureTypeTable COMM_Table[MAX_COUNTER_TABLE] = {0};

// DIRECT functions
void COMM_MakeMeasCommutateTable(uint16_t NumbTable, uint8_t Case, uint8_t TypeMeasure, uint8_t TypePositionOfCase,
		uint8_t TypeCtrl, uint8_t TypeSignalAsLeakAge, uint8_t SignalDirection, uint64_t NumRelay);

// Functions
uint16_t COMM_InitTable()
{
	// Измерение утечки
	COMM_MakeMeasCommutateTable(0, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(1, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(2, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV2_DIRECT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(3, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(4, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV3_DIRECT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(5, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV3_REVERSE	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(10, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,		ALIAS_HV1_DIRECT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(11, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(12, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,		ALIAS_HV2_DIRECT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(13, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(14, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,		ALIAS_HV3_DIRECT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(15, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV3_REVERSE	| ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(20, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_DIRECT,		ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(21, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(22, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_AC_V, LEAK_DC, PWR_DIRECT,		ALIAS_HV2_DIRECT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(23, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(24, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_AC_V, LEAK_DC, PWR_DIRECT,		ALIAS_HV3_DIRECT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(25, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV3_REVERSE	| ALIAS_CTRL1_DIRECT_NO_POT);

	COMM_MakeMeasCommutateTable(30, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(31, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4 | ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(32, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW5 | COMM_BUSLVMinusToPOW6 | ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(40, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(41, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4 | ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(42, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_DC_V_REVERSE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW4 | COMM_BUSLVMinusToPOW3 | ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(50, IGNORE, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(51, IGNORE, COMM_MEAS_CURR_LEAK, POS_2, CTRL_AC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4 | ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(52, IGNORE, COMM_MEAS_CURR_LEAK, POS_3, CTRL_AC_V, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW5 | COMM_BUSLVMinusToPOW6 | ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение падения напряжения
	COMM_MakeMeasCommutateTable(60, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(61, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(62, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(63, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(64, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(65, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(70, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(71, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(72, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(73, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(74, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(75, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(80, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(81, IGNORE, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(82, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(83, IGNORE, COMM_MEAS_DROP_VOLT, POS_2, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(84, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(85, IGNORE, COMM_MEAS_DROP_VOLT, POS_3, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение входного напряжения
	COMM_MakeMeasCommutateTable(90, IGNORE, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V,			IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(91, IGNORE, COMM_MEAS_IN_VOLT, IGNORE, CTRL_AC_V,			IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(92, IGNORE, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V_REVERSE,	IGNORE, IGNORE, ALIAS_CTRL1_REVERSE_POT);

	// Измерение напряжения запрета
	COMM_MakeMeasCommutateTable(100, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(101, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(102, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(103, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(104, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(105, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(110, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(111, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(112, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(113, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(114, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(115, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(120, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(121, IGNORE, COMM_MEAS_VOLT_BAN, POS_1, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(122, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(123, IGNORE, COMM_MEAS_VOLT_BAN, POS_2, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(124, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW3_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(125, IGNORE, COMM_MEAS_VOLT_BAN, POS_3, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	// Калибровка управления DC
	COMM_MakeMeasCommutateTable(160, IGNORE, COMM_CALIBRATE_DC_CONTROL, POS_1, IGNORE, IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(161, IGNORE, COMM_CALIBRATE_DC_CONTROL, POS_2, IGNORE, IGNORE, IGNORE, ALIAS_CTRL2_DIRECT_POT);

	// Калибровка вспомогательного питания
	COMM_MakeMeasCommutateTable(162, IGNORE, COMM_CALIBRATE_PS1, IGNORE, IGNORE, IGNORE, IGNORE, 0);
	COMM_MakeMeasCommutateTable(163, IGNORE, COMM_CALIBRATE_PS2, IGNORE, IGNORE, IGNORE, IGNORE, 0);

	// Калибровка утечки DC
	COMM_MakeMeasCommutateTable(164, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_1, IGNORE, LEAK_DC, PWR_DIRECT,		ALIAS_HV1_DIRECT);
	COMM_MakeMeasCommutateTable(165, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_1, IGNORE, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE);
	COMM_MakeMeasCommutateTable(166, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_2, IGNORE, LEAK_DC, PWR_DIRECT,		ALIAS_HV2_DIRECT);
	COMM_MakeMeasCommutateTable(167, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_2, IGNORE, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE);
	COMM_MakeMeasCommutateTable(168, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_3, IGNORE, LEAK_DC, PWR_DIRECT,		ALIAS_HV3_DIRECT);
	COMM_MakeMeasCommutateTable(169, IGNORE, COMM_CALIBRATE_DC_LEAKAGE, POS_3, IGNORE, LEAK_DC, PWR_REVERSE,	ALIAS_HV3_REVERSE);

	// Калибровка утечки AC
	COMM_MakeMeasCommutateTable(170, IGNORE, COMM_CALIBRATE_AC_LEAKAGE, POS_1, IGNORE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2);
	COMM_MakeMeasCommutateTable(171, IGNORE, COMM_CALIBRATE_AC_LEAKAGE, POS_2, IGNORE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW3 | COMM_BUSLVMinusToPOW4);
	COMM_MakeMeasCommutateTable(172, IGNORE, COMM_CALIBRATE_AC_LEAKAGE, POS_3, IGNORE, LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW5 | COMM_BUSLVMinusToPOW6);

	// Калибровка управления AC
	COMM_MakeMeasCommutateTable(173, IGNORE, COMM_CALIBRATE_AC_CONTROL, POS_1, IGNORE, IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(174, IGNORE, COMM_CALIBRATE_AC_CONTROL, POS_2, IGNORE, IGNORE, IGNORE, ALIAS_CTRL2_DIRECT_NO_POT);

	// Калибровка источника тока
	COMM_MakeMeasCommutateTable(178, IGNORE, COMM_CALIBRATE_CURRENT, POS_1, IGNORE, IGNORE, PWR_DIRECT,		ALIAS_POW1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(179, IGNORE, COMM_CALIBRATE_CURRENT, POS_1, IGNORE, IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(180, IGNORE, COMM_CALIBRATE_CURRENT, POS_2, IGNORE, IGNORE, PWR_DIRECT,		ALIAS_POW2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(181, IGNORE, COMM_CALIBRATE_CURRENT, POS_2, IGNORE, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT);
	COMM_MakeMeasCommutateTable(182, IGNORE, COMM_CALIBRATE_CURRENT, POS_3, IGNORE, IGNORE, PWR_DIRECT,		ALIAS_POW3_DIRECT_POT);
	COMM_MakeMeasCommutateTable(183, IGNORE, COMM_CALIBRATE_CURRENT, POS_3, IGNORE, IGNORE, PWR_REVERSE,	ALIAS_POW3_REVERSE_POT);

	// Специфические коммутации
	// Измерение утечки Л2, вторая позиция
	COMM_MakeMeasCommutateTable(200, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV2_DIRECT	| ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(201, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL2_DIRECT_POT);

	COMM_MakeMeasCommutateTable(202, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,	ALIAS_HV2_DIRECT	| ALIAS_CTRL2_REVERSE_POT);
	COMM_MakeMeasCommutateTable(203, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL2_REVERSE_POT);

	COMM_MakeMeasCommutateTable(204, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_AC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV2_DIRECT	| ALIAS_CTRL2_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(205, CASE_L2, COMM_MEAS_CURR_LEAK, POS_2, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV2_REVERSE	| ALIAS_CTRL2_DIRECT_NO_POT);

	// Измерение падения напряжения Л2, вторая позиция
	COMM_MakeMeasCommutateTable(210, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(211, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL2_DIRECT_POT);

	COMM_MakeMeasCommutateTable(212, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL2_REVERSE_POT);
	COMM_MakeMeasCommutateTable(213, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL2_REVERSE_POT);

	COMM_MakeMeasCommutateTable(214, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_AC_V, IGNORE, PWR_DIRECT,	ALIAS_POW2_DIRECT_POT	| ALIAS_CTRL2_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(215, CASE_L2, COMM_MEAS_DROP_VOLT, POS_2, CTRL_AC_V, IGNORE, PWR_REVERSE,	ALIAS_POW2_REVERSE_POT	| ALIAS_CTRL2_DIRECT_NO_POT);

	// Измерение входного напряжения, позиция 2
	COMM_MakeMeasCommutateTable(216, CASE_L2, COMM_MEAS_IN_VOLT, POS_2, CTRL_DC_V,			IGNORE, IGNORE, ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(217, CASE_L2, COMM_MEAS_IN_VOLT, POS_2, CTRL_AC_V,			IGNORE, IGNORE, ALIAS_CTRL2_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(218, CASE_L2, COMM_MEAS_IN_VOLT, POS_2, CTRL_DC_V_REVERSE,	IGNORE, IGNORE, ALIAS_CTRL2_REVERSE_POT);

	// Измерение утечки для приборов Б1
	COMM_MakeMeasCommutateTable(220, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(221, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(222, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(223, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(224, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(225, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_NO_POT);

	COMM_MakeMeasCommutateTable(226, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE,	LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(227, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V,			LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(228, CASE_B1, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V,			LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение утечки для приборов Б2
	COMM_MakeMeasCommutateTable(230, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(231, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(232, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(233, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_REVERSE_POT);

	COMM_MakeMeasCommutateTable(234, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_DIRECT,	ALIAS_HV1_DIRECT	| ALIAS_CTRL1_DIRECT_NO_POT);
	COMM_MakeMeasCommutateTable(235, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V, LEAK_DC, PWR_REVERSE,	ALIAS_HV1_REVERSE	| ALIAS_CTRL1_DIRECT_NO_POT);

	COMM_MakeMeasCommutateTable(236, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V_REVERSE,	LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(237, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_DC_V,			LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(238, CASE_B2, COMM_MEAS_CURR_LEAK, POS_1, CTRL_AC_V,			LEAK_AC, IGNORE, COMM_BUSLVPlusToPOW1 | COMM_BUSLVMinusToPOW2 | ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение падения напряжения для приборов Б1
	COMM_MakeMeasCommutateTable(240, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE,	IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(241, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V,			IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(242, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V,			IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	COMM_MakeMeasCommutateTable(243, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE,	IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(244, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V,			IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(245, CASE_B1, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V,			IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение падения напряжения для приборов Б2
	COMM_MakeMeasCommutateTable(250, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE,	IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(251, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V,			IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(252, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V,			IGNORE, PWR_DIRECT,	ALIAS_POW1_DIRECT_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	COMM_MakeMeasCommutateTable(253, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V_REVERSE,	IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(254, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_DC_V,			IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(255, CASE_B2, COMM_MEAS_DROP_VOLT, POS_1, CTRL_AC_V,			IGNORE, PWR_REVERSE,	ALIAS_POW1_REVERSE_POT	| ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение входного напряжения Б1
	COMM_MakeMeasCommutateTable(260, CASE_B1, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V_REVERSE,	IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(261, CASE_B1, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V,			IGNORE, IGNORE, ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(262, CASE_B1, COMM_MEAS_IN_VOLT, IGNORE, CTRL_AC_V,			IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение входного напряжения Б2
	COMM_MakeMeasCommutateTable(263, CASE_B2, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V_REVERSE,	IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(264, CASE_B2, COMM_MEAS_IN_VOLT, IGNORE, CTRL_DC_V,			IGNORE, IGNORE, ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(265, CASE_B2, COMM_MEAS_IN_VOLT, IGNORE, CTRL_AC_V,			IGNORE, IGNORE, ALIAS_CTRL1_DIRECT_NO_POT);

	// Измерение утечки А6, вторая позиция
	COMM_MakeMeasCommutateTable(270, CASE_A6, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_A6_HV2_DIRECT		| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(271, CASE_A6, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_A6_HV2_REVERSE	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(272, CASE_A6, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,	ALIAS_A6_HV2_DIRECT		| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(273, CASE_A6, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_A6_HV2_REVERSE	| ALIAS_CTRL1_REVERSE_POT);

	// Измерение падения напряжения A6, вторая позиция
	COMM_MakeMeasCommutateTable(275, CASE_A6, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_A6_POW2_DIRECT_POT	| ALIAS_CTRL1_DIRECT_POT);
	COMM_MakeMeasCommutateTable(276, CASE_A6, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_A6_POW2_REVERSE_POT	| ALIAS_CTRL1_DIRECT_POT);

	COMM_MakeMeasCommutateTable(277, CASE_A6, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_A6_POW2_DIRECT_POT	| ALIAS_CTRL1_REVERSE_POT);
	COMM_MakeMeasCommutateTable(278, CASE_A6, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_A6_POW2_REVERSE_POT	| ALIAS_CTRL1_REVERSE_POT);

	// Измерение утечки E2k, вторая позиция
	COMM_MakeMeasCommutateTable(280, CASE_E2k, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_DIRECT,	ALIAS_E2k_HV2_DIRECT	| ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(281, CASE_E2k, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V, LEAK_DC, PWR_REVERSE,	ALIAS_E2k_HV2_REVERSE	| ALIAS_CTRL2_DIRECT_POT);

	COMM_MakeMeasCommutateTable(282, CASE_E2k, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_DIRECT,	ALIAS_E2k_HV2_DIRECT	| ALIAS_CTRL2_REVERSE_POT);
	COMM_MakeMeasCommutateTable(283, CASE_E2k, COMM_MEAS_CURR_LEAK, POS_2, CTRL_DC_V_REVERSE, LEAK_DC, PWR_REVERSE,	ALIAS_E2k_HV2_REVERSE	| ALIAS_CTRL2_REVERSE_POT);

	// Измерение падения напряжения E2k, вторая позиция
	COMM_MakeMeasCommutateTable(285, CASE_E2k, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_DIRECT,	ALIAS_E2k_POW2_DIRECT_POT	| ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(286, CASE_E2k, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V, IGNORE, PWR_REVERSE,	ALIAS_E2k_POW2_REVERSE_POT	| ALIAS_CTRL2_DIRECT_POT);

	COMM_MakeMeasCommutateTable(287, CASE_E2k, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_DIRECT,	ALIAS_E2k_POW2_DIRECT_POT	| ALIAS_CTRL2_REVERSE_POT);
	COMM_MakeMeasCommutateTable(288, CASE_E2k, COMM_MEAS_DROP_VOLT, POS_2, CTRL_DC_V_REVERSE, IGNORE, PWR_REVERSE,	ALIAS_E2k_POW2_REVERSE_POT	| ALIAS_CTRL2_REVERSE_POT);

	// Измерение входного напряжения E2k, вторая позиция
	COMM_MakeMeasCommutateTable(290, CASE_E2k, COMM_MEAS_IN_VOLT, POS_2, CTRL_DC_V,			IGNORE, IGNORE, ALIAS_CTRL2_DIRECT_POT);
	COMM_MakeMeasCommutateTable(291, CASE_E2k, COMM_MEAS_IN_VOLT, POS_2, CTRL_DC_V_REVERSE,	IGNORE, IGNORE, ALIAS_CTRL2_REVERSE_POT);

	return MAX_COUNTER_TABLE;
}

void COMM_MakeMeasCommutateTable(uint16_t NumbTable, uint8_t Case, uint8_t TypeMeasure, uint8_t TypePositionOfCase,
		uint8_t TypeCtrl, uint8_t TypeSignalAsLeakAge, uint8_t SignalDirection, uint64_t NumRelay)
{
	COMM_Table[NumbTable].TypeMeasure = TypeMeasure;
	COMM_Table[NumbTable].Case = Case;
	COMM_Table[NumbTable].TypePositionOfCase = TypePositionOfCase;
	COMM_Table[NumbTable].TypeCtrl = TypeCtrl;
	COMM_Table[NumbTable].TypeSignalAsLeakAge = TypeSignalAsLeakAge;
	COMM_Table[NumbTable].SignalDirection = SignalDirection;
	COMM_Table[NumbTable].Relay = NumRelay;
	COMM_Table[NumbTable].Active = true;
}
